service: kms-stack-us-east-1

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  profile: nadtakanfuthoem-nadtakan

resources:
  Resources:
    serviceSharedDynamoDBCustomerManagedKey:
      Type: AWS::KMS::Key
      Properties:
        Description: Our symmetric key used to encrypt all DynamoDB tables in our application
        MultiRegion: true
        EnableKeyRotation: true
        KeyPolicy:
          Version: '2012-10-17'
          Id: serviceSharedDynamoDBKeyPolicy
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: Allow
              Principal:
                AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
              Action: kms:*
              Resource: '*'
            - Sid:  Allow DynamoDB to get information about the CMK
              Effect: Allow
              Principal:
                Service:
                  - dynamodb.amazonaws.com
              Action:
                - kms:Describe*
                - kms:Get*
                - kms:List*
              Resource: '*'

  Outputs:
    serviceSharedDynamoDBCustomerManagedKeyArn:
      Description: serviceSharedDynamoDBCustomerManagedKey Arn
      Value: 
        !GetAtt serviceSharedDynamoDBCustomerManagedKey.Arn
      Export:
        Name: serviceSharedDynamoDBCustomerManagedKeyArn-${self:provider.region}