service: aws-dynamodb-global-table

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1

custom:
  TableName: demo

resources:
  Resources:
    dynamodbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.TableName}
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
          KMSMasterKeyId:
            Fn::ImportValue: !Sub serviceSharedDynamoDBCustomerManagedKeyArn-us-east-1
          SSEType: KMS
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: timeToLive
          Enabled: true
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        Tags:
          - Key: env
            Value: demo-dynamodb-global-table

    dynamodbGlobalTable:
      Type: AWS::DynamoDB::GlobalTable
      Properties: 
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Replicas: 
          - ContributorInsightsSpecification: 
              Enabled: true
            Region: us-east-1
            TableClass: STANDARD
            SSESpecification:
              KMSMasterKeyId: 
                Fn::ImportValue: !Sub serviceSharedDynamoDBCustomerManagedKeyArn-us-east-1
            Tags: 
              - Key: env
                Value: demo-dynamodb-global-table
          - ContributorInsightsSpecification: 
              Enabled: true
            Region: us-west-1
            TableClass: STANDARD_INFREQUENT_ACCESS
            SSESpecification:
              KMSMasterKeyId: ${file(./kms-stacks/us-west-1/outputs.yml):KMSMasterKeyId} # can't cross stack ref, need work
            Tags: 
              - Key: env
                Value: demo-dynamodb-global-table
        TableName: ${self:custom.TableName}-global-tb
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
        TimeToLiveSpecification: 
          AttributeName: timeToLive
          Enabled: true