service: kms-stack-us-west-1

frameworkVersion: '3'

provider:
  name: aws
  region: us-west-1
  runtime: nodejs16.x
  profile: nadtakanfuthoem-nadtakan

custom:
  StackName: kms-stack-us-east-1-dev

functions:
  LookupStackOutputs:
    handler: index.handler
    timeout: 30
    role: LambdaExecutionRole

resources:
  Resources:
    # Cloud Formation Custom Resources
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: 
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 'arn:aws:logs:*:*:*'
                - Effect: Allow
                  Action:
                    - cloudformation:DescribeStacks
                  Resource: "*"

    DBStackReference:
      Type: Custom::ExternalStackReference
      Properties:
        ServiceToken:
          Fn::GetAtt: [LookupStackOutputsLambdaFunction, Arn]
        StackName: kms-stack-us-east-1-dev # Your desirable stack name you want to look up their output value
        Region: us-east-1 # Your desirable region that you want to look up their output value
        OutputKeys:
          - serviceSharedDynamoDBCustomerManagedKeyArn
                  
    serviceSharedDynamoDBCustomerManagedKeyReplicaKey:
      Type: AWS::KMS::ReplicaKey
      DependsOn: DBStackReference
      Properties: 
        Description: DynamoDB CMK Replica Key
        Enabled: true
        KeyPolicy:
          Version: '2012-10-17'
          Id: serviceSharedDynamoDBKeyPolicy
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: Allow
              Principal:
                AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
              Action: kms:*
              Resource: '*'
            - Sid:  Allow DynamoDB to get information about the CMK
              Effect: Allow
              Principal:
                Service:
                  - dynamodb.amazonaws.com
              Action:
                - kms:Describe*
                - kms:Get*
                - kms:List*
              Resource: '*'
        PrimaryKeyArn: 
          Fn::GetAtt: [DBStackReference,serviceSharedDynamoDBCustomerManagedKeyArn]
        Tags:
          - Key: env
            Value: demo-dynamodb-global-table

  Outputs:
    serviceSharedDynamoDBCustomerManagedKeyReplicaKey:
      Description: serviceSharedDynamoDBCustomerManagedKeyReplicaKey Arn
      Value: !GetAtt serviceSharedDynamoDBCustomerManagedKeyReplicaKey.Arn
      Export:
        Name: serviceSharedDynamoDBCustomerManagedKeyReplicaKey-${self:provider.region}
    
    serviceSharedDynamoDBCustomerManagedKeyReplicaKeyId:
      Description: serviceSharedDynamoDBCustomerManagedKeyReplicaKey
      Value: !GetAtt serviceSharedDynamoDBCustomerManagedKeyReplicaKey.Arn
      Export:
        Name: serviceSharedDynamoDBCustomerManagedKeyReplicaKeyId-${self:provider.region}